In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/dhwanit75/Learning-form-Errors/main/Assignment-1/hotel_bookings.csv")
print("Data imported Successfully")

Data imported Successfully

In [148]:
X=df

X.dropna(how='all', inplace=True)
X.interpolate()
X.dropna(how='any', inplace=True,axis=1)


# X=X.drop(['adr'],axis=1)
# y=df['adr']

In [149]:
X.shape

(119390, 28)

In [150]:
add=pd.get_dummies(X.arrival_date_month)
X=pd.concat([add,X],axis=1)
X.dropna(axis=1)
X=X.drop(['arrival_date_month'],axis=1)
X

,April,August,December,February,January,July,June,March,May,November,October,September,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,0,0,0,0,0,1,0,0,0,0,0,0,Resort Hotel,0,342,2015,27,1,0,0,2,0,BB,Direct,Direct,0,0,0,C,C,3,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,0,0,0,0,0,1,0,0,0,0,0,0,Resort Hotel,0,737,2015,27,1,0,0,2,0,BB,Direct,Direct,0,0,0,C,C,4,No Deposit,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,0,0,0,0,0,1,0,0,0,0,0,0,Resort Hotel,0,7,2015,27,1,0,1,1,0,BB,Direct,Direct,0,0,0,A,C,0,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,0,0,0,0,0,1,0,0,0,0,0,0,Resort Hotel,0,13,2015,27,1,0,1,1,0,BB,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,0,0,0,0,0,1,0,0,0,0,0,0,Resort Hotel,0,14,2015,27,1,0,2,2,0,BB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,1,0,0,0,0,0,0,0,0,0,0,City Hotel,0,23,2017,35,30,2,5,2,0,BB,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,0,1,0,0,0,0,0,0,0,0,0,0,City Hotel,0,102,2017,35,31,2,5,3,0,BB,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,0,1,0,0,0,0,0,0,0,0,0,0,City Hotel,0,34,2017,35,31,2,5,2,0,BB,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,0,1,0,0,0,0,0,0,0,0,0,0,City Hotel,0,109,2017,35,31,2,5,2,0,BB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,0,1,0,0,0,0,0,0,0,0,0,0,City Hotel,0,205,2017,35,29,2,7,2,0,HB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [151]:
add=pd.get_dummies(X.hotel)
X=pd.concat([add,X],axis=1)
X=X.drop(['hotel'],axis=1)
X.head()

,City Hotel,Resort Hotel,April,August,December,February,January,July,June,March,May,November,October,September,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,342,2015,27,1,0,0,2,0,BB,Direct,Direct,0,0,0,C,C,3,No Deposit,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,737,2015,27,1,0,0,2,0,BB,Direct,Direct,0,0,0,C,C,4,No Deposit,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,7,2015,27,1,0,1,1,0,BB,Direct,Direct,0,0,0,A,C,0,No Deposit,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,13,2015,27,1,0,1,1,0,BB,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,14,2015,27,1,0,2,2,0,BB,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [152]:
add=pd.get_dummies(X.meal)
X=pd.concat([add,X],axis=1)
X=X.drop(['meal'],axis=1)
X.head()

,BB,FB,HB,SC,Undefined,City Hotel,Resort Hotel,April,August,December,February,January,July,June,March,May,November,October,September,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,babies,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,342,2015,27,1,0,0,2,0,Direct,Direct,0,0,0,C,C,3,No Deposit,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,737,2015,27,1,0,0,2,0,Direct,Direct,0,0,0,C,C,4,No Deposit,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,7,2015,27,1,0,1,1,0,Direct,Direct,0,0,0,A,C,0,No Deposit,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,13,2015,27,1,0,1,1,0,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,14,2015,27,1,0,2,2,0,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [153]:
add=pd.get_dummies(X.reservation_status)
X=pd.concat([add,X],axis=1)
X=X.drop(['reservation_status'],axis=1)
X.head()

,Canceled,Check-Out,No-Show,BB,FB,HB,SC,Undefined,City Hotel,Resort Hotel,April,August,December,February,January,July,June,March,May,November,October,September,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,babies,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date
0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,342,2015,27,1,0,0,2,0,Direct,Direct,0,0,0,C,C,3,No Deposit,0,Transient,0.0,0,0,2015-07-01
1,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,737,2015,27,1,0,0,2,0,Direct,Direct,0,0,0,C,C,4,No Deposit,0,Transient,0.0,0,0,2015-07-01
2,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,7,2015,27,1,0,1,1,0,Direct,Direct,0,0,0,A,C,0,No Deposit,0,Transient,75.0,0,0,2015-07-02
3,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,13,2015,27,1,0,1,1,0,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,Transient,75.0,0,0,2015-07-02
4,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,14,2015,27,1,0,2,2,0,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,98.0,0,1,2015-07-03

In [154]:
X=X.drop(['reservation_status_date'],axis=1)

In [155]:
add=pd.get_dummies(X.customer_type)
X=pd.concat([add,X],axis=1)
X=X.drop(['customer_type'],axis=1)
X.head()

,Contract,Group,Transient,Transient-Party,Canceled,Check-Out,No-Show,BB,FB,HB,SC,Undefined,City Hotel,Resort Hotel,April,August,December,February,January,July,June,March,May,November,October,September,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,babies,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,342,2015,27,1,0,0,2,0,Direct,Direct,0,0,0,C,C,3,No Deposit,0,0.0,0,0
1,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,737,2015,27,1,0,0,2,0,Direct,Direct,0,0,0,C,C,4,No Deposit,0,0.0,0,0
2,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,7,2015,27,1,0,1,1,0,Direct,Direct,0,0,0,A,C,0,No Deposit,0,75.0,0,0
3,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,13,2015,27,1,0,1,1,0,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,75.0,0,0
4,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,14,2015,27,1,0,2,2,0,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,98.0,0,1

In [156]:
add=pd.get_dummies(X.deposit_type)
X=pd.concat([add,X],axis=1)
X=X.drop(['deposit_type'],axis=1)
X.head()

,No Deposit,Non Refund,Refundable,Contract,Group,Transient,Transient-Party,Canceled,Check-Out,No-Show,BB,FB,HB,SC,Undefined,City Hotel,Resort Hotel,April,August,December,February,January,July,June,March,May,November,October,September,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,babies,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,342,2015,27,1,0,0,2,0,Direct,Direct,0,0,0,C,C,3,0,0.0,0,0
1,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,737,2015,27,1,0,0,2,0,Direct,Direct,0,0,0,C,C,4,0,0.0,0,0
2,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,7,2015,27,1,0,1,1,0,Direct,Direct,0,0,0,A,C,0,0,75.0,0,0
3,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,13,2015,27,1,0,1,1,0,Corporate,Corporate,0,0,0,A,A,0,0,75.0,0,0
4,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,14,2015,27,1,0,2,2,0,Online TA,TA/TO,0,0,0,A,A,0,0,98.0,0,1

In [157]:
add=pd.get_dummies(X.assigned_room_type)
X=pd.concat([add,X],axis=1)
X=X.drop(['assigned_room_type'],axis=1)
X.head()

,A,B,C,D,E,F,G,H,I,K,L,P,No Deposit,Non Refund,Refundable,Contract,Group,Transient,Transient-Party,Canceled,Check-Out,No-Show,BB,FB,HB,SC,Undefined,City Hotel,Resort Hotel,April,August,December,February,January,July,June,March,May,November,October,September,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,babies,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,342,2015,27,1,0,0,2,0,Direct,Direct,0,0,0,C,3,0,0.0,0,0
1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,737,2015,27,1,0,0,2,0,Direct,Direct,0,0,0,C,4,0,0.0,0,0
2,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,7,2015,27,1,0,1,1,0,Direct,Direct,0,0,0,A,0,0,75.0,0,0
3,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,13,2015,27,1,0,1,1,0,Corporate,Corporate,0,0,0,A,0,0,75.0,0,0
4,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,14,2015,27,1,0,2,2,0,Online TA,TA/TO,0,0,0,A,0,0,98.0,0,1

In [158]:
add=pd.get_dummies(X.market_segment)
X=pd.concat([add,X],axis=1)
X=X.drop(['market_segment'],axis=1)
X.head()

,Aviation,Complementary,Corporate,Direct,Groups,Offline TA/TO,Online TA,Undefined,A,B,C,D,E,F,G,H,I,K,L,P,No Deposit,Non Refund,Refundable,Contract,Group,Transient,Transient-Party,Canceled,Check-Out,No-Show,BB,FB,HB,SC,Undefined,City Hotel,Resort Hotel,April,August,December,February,January,July,June,March,May,November,October,September,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,babies,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,342,2015,27,1,0,0,2,0,Direct,0,0,0,C,3,0,0.0,0,0
1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,737,2015,27,1,0,0,2,0,Direct,0,0,0,C,4,0,0.0,0,0
2,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,7,2015,27,1,0,1,1,0,Direct,0,0,0,A,0,0,75.0,0,0
3,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,13,2015,27,1,0,1,1,0,Corporate,0,0,0,A,0,0,75.0,0,0
4,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,14,2015,27,1,0,2,2,0,TA/TO,0,0,0,A,0,0,98.0,0,1

In [159]:
add=pd.get_dummies(X.distribution_channel)
X=pd.concat([add,X],axis=1)
X=X.drop(['distribution_channel'],axis=1)
X.head()

,Corporate,Direct,GDS,TA/TO,Undefined,Aviation,Complementary,Corporate,Direct,Groups,Offline TA/TO,Online TA,Undefined,A,B,C,D,E,F,G,H,I,K,L,P,No Deposit,Non Refund,Refundable,Contract,Group,Transient,Transient-Party,Canceled,Check-Out,No-Show,BB,FB,HB,SC,Undefined,City Hotel,Resort Hotel,April,August,December,February,January,July,June,March,May,November,October,September,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,342,2015,27,1,0,0,2,0,0,0,0,C,3,0,0.0,0,0
1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,737,2015,27,1,0,0,2,0,0,0,0,C,4,0,0.0,0,0
2,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,7,2015,27,1,0,1,1,0,0,0,0,A,0,0,75.0,0,0
3,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,13,2015,27,1,0,1,1,0,0,0,0,A,0,0,75.0,0,0
4,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,14,2015,27,1,0,2,2,0,0,0,0,A,0,0,98.0,0,1

In [160]:
X=X.drop(['reserved_room_type'],axis=1)

In [161]:
# def calc_smooth_mean(dft, by, on, m):
#     # Compute the global mean
#     mean = dft[on].mean()

#     # Compute the number of values and the mean of each group
#     agg = dft.groupby(by)[on].agg(['count', 'mean'])
#     counts = agg['count']
#     means = agg['mean']

#     # Compute the "smoothed" means
#     smooth = (counts * means + m * mean) / (counts + m)

#     # Replace each value by the according smoothed mean
#     return dft[by].map(smooth)
# X['country'] = calc_smooth_mean(df, by='country', on='adr', m=10)

In [162]:
#pd.options.display.max_rows = 4000
print(X.dtypes)

Corporate                           uint8
Direct                              uint8
GDS                                 uint8
TA/TO                               uint8
Undefined                           uint8
Aviation                            uint8
Complementary                       uint8
Corporate                           uint8
Direct                              uint8
Groups                              uint8
Offline TA/TO                       uint8
Online TA                           uint8
Undefined                           uint8
A                                   uint8
B                                   uint8
C                                   uint8
D                                   uint8
E                                   uint8
F                                   uint8
G                                   uint8
H                                   uint8
I                                   uint8
K                                   uint8
L                                   uint8
P                                   uint8
No Deposit                          uint8
Non Refund                          uint8
Refundable                          uint8
Contract                            uint8
Group                               uint8
Transient                           uint8
Transient-Party                     uint8
Canceled                            uint8
Check-Out                           uint8
No-Show                             uint8
BB                                  uint8
FB                                  uint8
HB                                  uint8
SC                                  uint8
Undefined                           uint8
City Hotel                          uint8
Resort Hotel                        uint8
April                               uint8
August                              uint8
December                            uint8
February                            uint8
January                             uint8
July                                uint8
June                                uint8
March                               uint8
May                                 uint8
November                            uint8
October                             uint8
September                           uint8
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
babies                              int64
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
booking_changes                     int64
days_in_waiting_list                int64
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
dtype: object

In [163]:
pd.options.display.max_columns = 100
X.describe()

,Corporate,Direct,GDS,TA/TO,Undefined,Aviation,Complementary,Corporate,Direct,Groups,Offline TA/TO,Online TA,Undefined,A,B,C,D,E,F,G,H,I,K,L,P,No Deposit,Non Refund,Refundable,Contract,Group,Transient,Transient-Party,Canceled,Check-Out,No-Show,BB,FB,HB,SC,Undefined,City Hotel,Resort Hotel,April,August,December,February,January,July,June,March,May,November,October,September,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.00000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.055926,0.122665,0.001617,0.819750,0.000042,0.001985,0.006223,0.044350,0.105587,0.165935,0.202856,0.473046,0.000017,0.620261,0.018117,0.019893,0.212095,0.065382,0.031418,0.021384,0.005964,0.003040,0.002337,0.000008,0.000101,0.876464,0.122179,0.001357,0.03414,0.004833,0.750591,0.210436,0.360307,0.629584,0.010110,0.773180,0.006684,0.121141,0.089203,0.009791,0.664461,0.335539,0.092880,0.116233,0.056789,0.067577,0.049661,0.106047,0.091624,0.082034,0.098760,0.056906,0.093475,0.088014,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.007949,0.031912,0.087118,0.137097,0.221124,2.321149,101.831122,0.062518,0.571363
std,0.229780,0.328054,0.040174,0.384397,0.006471,0.044510,0.078642,0.205873,0.307309,0.372024,0.402128,0.499275,0.004093,0.485324,0.133375,0.139632,0.408793,0.247200,0.174445,0.144660,0.076994,0.055057,0.048285,0.002894,0.010025,0.329053,0.327494,0.036811,0.18159,0.069351,0.432673,0.407620,0.480091,0.482918,0.100038,0.418777,0.081482,0.326292,0.285038,0.098466,0.472181,0.472181,0.290266,0.320505,0.231439,0.251019,0.217244,0.307900,0.288496,0.274417,0.298341,0.231664,0.291098,0.283317,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.097436,0.175767,0.844336,1.497437,0.652306,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,94.575000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,1.000000,26.000000,72.000000,21.000000,391.000000,5400.000000,8.000000,5.000000

In [164]:
X.shape
U=X

In [189]:
X=U
shortlisting=['lead_time','stays_in_week_nights','adults']
for i in shortlisting:
    min_t,max_t=(X[i].quantile([0.01,0.99]))
    
    X=X[(X[i]<max_t)&(X[i]>min_t)]
    print(X.shape)

(111827, 71)
(104137, 71)
(79525, 71)

In [190]:
y=X['adr']
X=X.drop(['adr'],axis=1)

In [191]:
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LogisticRegression
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score

In [192]:
pipe1=Pipeline([
    ("scale",StandardScaler()),
    ("model",KNeighborsRegressor())
])

# Cross-Validation of diff. models

In [193]:
# Multiply by -1 since sklearn calculates *negative* MAE
scores1 = -1 * cross_val_score(pipe1, X, y, cv=5,scoring='neg_mean_absolute_error')
print("MAE scores1:\n", scores1)

MAE scores1:
 [27.13108783 27.38156467 26.03820031 20.03392468 23.57993273]

In [194]:
print("Average MAE score (across experiment-1):")
print(scores1.mean())

Average MAE score (across experiment-1):
24.83294204338258

In [ ]:
# pipe1.fit(X,y)
# plt.scatter(pipe1.predict(X),y)

In [196]:
pipe2=Pipeline([
    ("scale",StandardScaler()),
    ("model",LinearRegression())
])

In [197]:
scores2 = -1 * cross_val_score(pipe2, X, y, cv=5,scoring='neg_mean_absolute_error')
print("MAE scores2:\n", scores2)

MAE scores2:
 [29.54794736 31.43898707 19.41630402 22.24056109 21.26795363]

In [198]:
print("Average MAE score (across experiment-2):")
print(scores2.mean())

Average MAE score (across experiment-2):
24.782350635473545

In [199]:
pipe3=Pipeline([
    ("scale",StandardScaler()),
    ("model",KNeighborsRegressor())
])

In [201]:
scores3 = -1 * cross_val_score(pipe3, X, y, cv=5,scoring='neg_mean_absolute_error')
print("MAE scores3:\n", scores3)
print("Average MAE score (across experiment-3):")
print(scores3.mean())

MAE scores2:
 [27.13108783 27.38156467 26.03820031 20.03392468 23.57993273]
Average MAE score (across experiment-3):
24.83294204338258

In [203]:
pipe4=Pipeline([
    ("scale",StandardScaler()),
    ("model",RandomForestRegressor())
])

In [204]:
scores4 = -1 * cross_val_score(pipe4, X, y, cv=5,scoring='neg_mean_absolute_error')
print("MAE scores4:\n", scores4)
print("Average MAE score (across experiment-4):")
print(scores4.mean())

MAE scores4:
 [20.57210516 16.71949165 13.10225976 14.87769188 14.39038635]
Average MAE score (across experiment-4):
15.932386959250962

In [211]:
pipe5=Pipeline([
    ("scale",StandardScaler()),
    ("model",XGBRegressor())
])

In [212]:
scores5 = -1 * cross_val_score(pipe5, X, y, cv=5,scoring='neg_mean_absolute_error')
print("MAE scores5:\n", scores5)
print("Average MAE score (across experiment-5):")
print(scores5.mean())

MAE scores5:
 [18.08592093 18.01405664 12.84455271 14.4060011  14.68571987]
Average MAE score (across experiment-5):
15.60725024876055